//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.1
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puz.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("puz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _0 {
            get {
                object obj = ResourceManager.GetObject("0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1_2_beach_ball_png_picture_thumb {
            get {
                object obj = ResourceManager.GetObject("1-2-beach-ball-png-picture-thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _210229_vaporwave_wallpaper_1920x1080_1920x1080_for_pc__1_ {
            get {
                object obj = ResourceManager.GetObject("210229-vaporwave-wallpaper-1920x1080-1920x1080-for-pc (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _210240_popular_vaporwave_wallpaper_1920x1080_1920x1080_cell_phone {
            get {
                object obj = ResourceManager.GetObject("210240-popular-vaporwave-wallpaper-1920x1080-1920x1080-cell-phone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _233244488123212 {
            get {
                object obj = ResourceManager.GetObject("233244488123212", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _240196452007212 {
            get {
                object obj = ResourceManager.GetObject("240196452007212", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _279240_full_size_vaporwave_wallpaper_1920x1280_windows_7 {
            get {
                object obj = ResourceManager.GetObject("279240-full-size-vaporwave-wallpaper-1920x1280-windows-7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abelar10 {
            get {
                object obj = ResourceManager.GetObject("abelar10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_789d2ca5aee4_128 {
            get {
                object obj = ResourceManager.GetObject("avatar_789d2ca5aee4_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bu {
            get {
                object obj = ResourceManager.GetObject("bu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CaJ89hlWEAAgUa3 {
            get {
                object obj = ResourceManager.GetObject("CaJ89hlWEAAgUa3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap car {
            get {
                object obj = ResourceManager.GetObject("car", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DimLoneGroundbeetle_100px {
            get {
                object obj = ResourceManager.GetObject("DimLoneGroundbeetle-100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dolphin_vaporwave_png_6 {
            get {
                object obj = ResourceManager.GetObject("dolphin-vaporwave-png-6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap download1 {
            get {
                object obj = ResourceManager.GetObject("download1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flat_800x800_070_f_u1 {
            get {
                object obj = ResourceManager.GetObject("flat,800x800,070,f.u1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flat_800x800_075_f {
            get {
                object obj = ResourceManager.GetObject("flat,800x800,075,f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flat_800x800_075_f_u1 {
            get {
                object obj = ResourceManager.GetObject("flat,800x800,075,f.u1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flat_800x800_075_f1 {
            get {
                object obj = ResourceManager.GetObject("flat,800x800,075,f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap glitch_japan_vaporwave_ulica {
            get {
                object obj = ResourceManager.GetObject("glitch-japan-vaporwave-ulica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap how_to_draw_backpack_from_dora_the_explorer {
            get {
                object obj = ResourceManager.GetObject("how-to-draw-backpack-from-dora-the-explorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maxresdefault {
            get {
                object obj = ResourceManager.GetObject("maxresdefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNGPIX_COM_Kite_PNG_Transparent_Image_500x469 {
            get {
                object obj = ResourceManager.GetObject("PNGPIX-COM-Kite-PNG-Transparent-Image-500x469", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pr4422222_1d40af9d69b63c96 {
            get {
                object obj = ResourceManager.GetObject("pr4422222_1d40af9d69b63c96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sticker_220x200_bg_ffffff_pad_220x200_ffffff_u1 {
            get {
                object obj = ResourceManager.GetObject("sticker,220x200-bg,ffffff-pad,220x200,ffffff.u1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Swordfish__Aquarium_ {
            get {
                object obj = ResourceManager.GetObject("Swordfish_(Aquarium)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tag_do_brinquedo {
            get {
                object obj = ResourceManager.GetObject("tag do brinquedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap th {
            get {
                object obj = ResourceManager.GetObject("th", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tumblr_oecjtsrnIh1vgfej1o1_1280 {
            get {
                object obj = ResourceManager.GetObject("tumblr_oecjtsrnIh1vgfej1o1_1280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tumblr_static_b771xkdptlsg04sccsk048ssw_640_v2 {
            get {
                object obj = ResourceManager.GetObject("tumblr_static_b771xkdptlsg04sccsk048ssw_640_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap urso {
            get {
                object obj = ResourceManager.GetObject("urso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vektroid_600 {
            get {
                object obj = ResourceManager.GetObject("vektroid-600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vhs_1510074805060_7292 {
            get {
                object obj = ResourceManager.GetObject("vhs-1510074805060-7292", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vhs_1510074818514_149 {
            get {
                object obj = ResourceManager.GetObject("vhs-1510074818514-149", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wallhaven375075 {
            get {
                object obj = ResourceManager.GetObject("wallhaven375075", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
